## Tensorflow 

In [4]:
import tensorflow as tf

2021-08-21 16:40:25.815000: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-21 16:40:25.815049: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [5]:
tf.__version__

'2.6.0'

In [9]:
#create constants with tf.constant

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
scalar.ndim

0

In [10]:
vector = tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [11]:
vector1 = tf.constant([2.4,3.2])
vector1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.4, 3.2], dtype=float32)>

In [13]:
matrix = tf.constant([[2,3,4],[3,2,4]])
print(matrix)

tf.Tensor(
[[2 3 4]
 [3 2 4]], shape=(2, 3), dtype=int32)


In [14]:
matrix.ndim

2

In [15]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [17]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# let's do with TF.Variable()

In [18]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [20]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
unchangeable_tensor[0].assign(8) # cannot change

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Random tensors

In [26]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# shuffle tensors

In [29]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [5,4]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  4],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [32]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  4]], dtype=int32)>

In [36]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  4]], dtype=int32)>

In [37]:
tf.ones([4,6])

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [38]:
# Make a tensor of all ones
tf.ones(shape=(3, 2))


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [39]:

# Make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [40]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [41]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [42]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [43]:

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [44]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [45]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [47]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [48]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Manipulating tensors

In [50]:
tensor = tf.constant([[12,3],[23,43]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  3],
       [23, 43]], dtype=int32)>

In [51]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 13],
       [33, 53]], dtype=int32)>

In [52]:
a = tf.constant([2,4,6])
b = tf.constant([2,2,2])
c = tf.math.divide(a, b, name=None)
c

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

# Matrix multiplication

In [54]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[12  3]
 [23 43]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 213,  165],
       [1265, 1918]], dtype=int32)>

In [55]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 213,  165],
       [1265, 1918]], dtype=int32)>

In [56]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [57]:
# Try to matrix multiply them (will error)
# X @ Y won't work. because the shape is not proper

In [59]:
X @ tf.reshape(Y, shape=(2,3)) # this works because it's in proper shape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [60]:
D = tf.constant([-2,-3])

In [61]:
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -3], dtype=int32)>

In [62]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [63]:
E = tf.constant(np.random.randint(0,100, size= 50))

In [64]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 8, 19, 11,  6, 94, 25, 41, 69, 17, 85, 29, 25, 71, 65, 93, 23,  2,
       98, 32, 15, 27, 15,  9, 26, 29, 87, 59, 77, 92, 43, 17, 44, 41, 13,
        1,  1,  5, 24, 46,  4, 33, 14, 62, 93, 56, 76, 27, 30, 66, 77])>

In [70]:
# tf.reduce_mean(E),
tf.reduce_max(E)
tf.reduce_min(E)
tf.reduce_prod(E)

<tf.Tensor: shape=(), dtype=int64, numpy=-6607795687268548608>

## Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [71]:
tf.constant([12,23]) # vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 23], dtype=int32)>

In [72]:
tf.constant(6) # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [78]:
 I = tf.constant([[12,32,67],
            [12,43,34]]) # matrix

In [79]:
I

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 32, 67],
       [12, 43, 34]], dtype=int32)>

In [80]:
tf.shape(I)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [81]:
tf.size(I)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [82]:
tf.rank(I)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [87]:
g = tf.random.Generator.from_seed(42)
g.normal(shape=(5, 300))

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
        -1.0722276 , -0.00586287],
       [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
         1.155565  , -0.10707551],
       [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
         1.216793  , -1.24293   ],
       [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
        -0.73970354,  0.0177109 ],
       [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
         0.5656089 ,  0.18439196]], dtype=float32)>